### ISSUE TITLE
Create agent metadata spec

### ISSUE THREAD

**Issue by matoushavlena** [i-am-bee/beeai-platform#431]
Discussion: https://github.com/orgs/i-am-bee/discussions/432

Define various agent metadata (such as description, license, failure rate, tokens consumed, capabilities, ...). Agent should also be able to provide info on the default models/LLM providers. Come up with a spec.

**Comment by matoushavlena** [comment]
- capabilities
  - threads/session/state
  - streaming
- tags / specializations
- models
- protocol versions
- manufacturer / developed by / ownership

**Comment by matoushavlena** [comment]
```yaml
manifestVersion: 2
kind: Agent
from: "node:20 | python:3.11 | ghcr.io/i-am-bee/identity-agent#v1.2.3"

name: "identity-agent"
description: "Provides same output as input"

## just an exmaple if we need to specify input and output
input: "chat"
output: "chat"


## configuration
env:
- name: GOOGLE_API_KEY
  required: false
  description: "Google Search API key"
```
